- name: create ec2 instances and r53 records
  hosts: localhost
  connection: local

  vars_files:
    - vars.yaml

  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: create route53 record
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"

    - name: create route53 record for frontend
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite: true
      when: item.item == "frontend"
      loop: "{{ ec2_output.results }}"
