
- name: Launch EC2 and create Route53 record
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ aws_region }}"
        wait: yes
        count: 1
        security_group: "{{ security_group }}"
        tags:
          Environment: Test
          Name: "{{ instance_name }}"
      register: ec2

    - name: Set public IP as a fact
      set_fact:
        ec2_public_ip: "{{ ec2.instances[0].public_ip_address }}"

    - name: Create a Route53 A record
      community.aws.route53:
        state: present
        zone: "{{ hosted_zone_id }}"
        record: "{{ record_name }}"
        type: A
        ttl: 300
        value: "{{ ec2_public_ip }}"
        aws_region: "{{ aws_region }}"
